# Generated by Django 5.2.4 on 2025-11-08 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userface'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='master_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('created_rows', models.IntegerField(default=0)),
                ('updated_rows', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
