# Generated by Django 5.2.4 on 2025-11-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_masterdatafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('enrollment_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(max_length=10)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='master_faces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MasterDataFile',
        ),
    ]
