# Generated by Django 5.2.4 on 2025-11-08 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_masteruserrecord_delete_masterdatafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruserrecord',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masteruserrecord',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='masteruserrecord',
            name='enrollment_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='masteruserrecord',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/master_faces/'),
        ),
        migrations.AlterField(
            model_name='masteruserrecord',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], max_length=20),
        ),
        migrations.AlterField(
            model_name='masteruserrecord',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
